// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserModelImpl _$$UserModelImplFromJson(Map<String, dynamic> json) =>
    _$UserModelImpl(
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => UserData.fromJson(e as Map<String, dynamic>))
          .toList(),
      msg: json['msg'] as String?,
    );

Map<String, dynamic> _$$UserModelImplToJson(_$UserModelImpl instance) =>
    <String, dynamic>{
      'data': instance.data,
      'msg': instance.msg,
    };

_$UserDataImpl _$$UserDataImplFromJson(Map<String, dynamic> json) =>
    _$UserDataImpl(
      id: json['id'] as String?,
      countryCode: json['country_code'] as String?,
      languageCode: json['language_code'] as String?,
      userTypeId: json['user_type_id'] as String?,
      genderId: json['gender_id'] as String?,
      name: json['name'] as String?,
      photo: json['photo'] as String?,
      about: json['about'] as String?,
      phone: json['phone'] as String?,
      phoneHidden: json['phone_hidden'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      emailVerifiedAt: json['email_verified_at'] as String?,
      password: json['password'] as String?,
      rememberToken: json['remember_token'] as String?,
      isAdmin: json['is_admin'] as String?,
      canBeImpersonated: json['can_be_impersonated'] as String?,
      disableComments: json['disable_comments'] as String?,
      ipAddr: json['ip_addr'] as String?,
      provider: json['provider'] as String?,
      providerId: json['provider_id'] as String?,
      emailToken: json['email_token'] as String?,
      phoneToken: json['phone_token'] as String?,
      verifiedEmail: json['verified_email'] as String?,
      verifiedPhone: json['verified_phone'] as String?,
      acceptTerms: json['accept_terms'] as String?,
      acceptMarketingOffers: json['accept_marketing_offers'] as String?,
      timeZone: json['time_zone'] as String?,
      blocked: json['blocked'] as String?,
      closed: json['closed'] as String?,
      lastActivity: json['last_activity'] as String?,
      lastLoginAt: json['last_login_at'] as String?,
      ims: json['ims'] as String?,
      brandbazar: json['brandbazar'] as String?,
      brandbazarVerify: json['brandbazar_verify'] as String?,
      brandbazarStatus: json['brandbazar_status'] as String?,
      brandbazarPaymentStatus: json['brandbazar_payment_status'] as String?,
      paymentQr: json['payment_qr'] as String?,
      bankName: json['bank_name'] as String?,
      bankBranch: json['bank_branch'] as String?,
      acHolder: json['ac_holder'] as String?,
      acNumber: json['ac_number'] as String?,
      banner: json['banner'] as String?,
      description: json['description'] as String?,
      panVat: json['pan_vat'] as String?,
      taxCertificate: json['tax_certificate'] as String?,
      registerCertificate: json['register_certificate'] as String?,
      userVerify: json['user_verify'] as String?,
      gender: json['gender'] as String?,
      dob: json['dob'] as String?,
      deletedAt: json['deleted_at'] as String?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
    );

Map<String, dynamic> _$$UserDataImplToJson(_$UserDataImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'country_code': instance.countryCode,
      'language_code': instance.languageCode,
      'user_type_id': instance.userTypeId,
      'gender_id': instance.genderId,
      'name': instance.name,
      'photo': instance.photo,
      'about': instance.about,
      'phone': instance.phone,
      'phone_hidden': instance.phoneHidden,
      'username': instance.username,
      'email': instance.email,
      'email_verified_at': instance.emailVerifiedAt,
      'password': instance.password,
      'remember_token': instance.rememberToken,
      'is_admin': instance.isAdmin,
      'can_be_impersonated': instance.canBeImpersonated,
      'disable_comments': instance.disableComments,
      'ip_addr': instance.ipAddr,
      'provider': instance.provider,
      'provider_id': instance.providerId,
      'email_token': instance.emailToken,
      'phone_token': instance.phoneToken,
      'verified_email': instance.verifiedEmail,
      'verified_phone': instance.verifiedPhone,
      'accept_terms': instance.acceptTerms,
      'accept_marketing_offers': instance.acceptMarketingOffers,
      'time_zone': instance.timeZone,
      'blocked': instance.blocked,
      'closed': instance.closed,
      'last_activity': instance.lastActivity,
      'last_login_at': instance.lastLoginAt,
      'ims': instance.ims,
      'brandbazar': instance.brandbazar,
      'brandbazar_verify': instance.brandbazarVerify,
      'brandbazar_status': instance.brandbazarStatus,
      'brandbazar_payment_status': instance.brandbazarPaymentStatus,
      'payment_qr': instance.paymentQr,
      'bank_name': instance.bankName,
      'bank_branch': instance.bankBranch,
      'ac_holder': instance.acHolder,
      'ac_number': instance.acNumber,
      'banner': instance.banner,
      'description': instance.description,
      'pan_vat': instance.panVat,
      'tax_certificate': instance.taxCertificate,
      'register_certificate': instance.registerCertificate,
      'user_verify': instance.userVerify,
      'gender': instance.gender,
      'dob': instance.dob,
      'deleted_at': instance.deletedAt,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
    };
