// FormData formData = FormData.fromMap({
//   'tags': [],
//   'category_id': "15",
//   'post_type_id': "2",
//   'title': "asdadasdasdaasdasdasdasd",
//   'description': "7 port usb hub in black color with switch",
//   'contact_name': "Prajen Shakya",
//   'auth_field': "phone",
//   'phone': "9813465780",
//   'phone_country': "NP",
//   'city_id': "16",
//   'accept_terms': "1",
//   'email': "shakyaprajen@gmail.com",
//   'country_code': "NP",
//   'price': "750",
//   'discounted_price': "1000",
//   'negotiable': "0",
//   'phone_hidden': "1",
//   'captcha': "embed",
//   'ip_addr': "127.0.0.1",
//   'accept_marketing_offers': "1",
//   'is_permanent': "0",
//   'package_id': "1",
//   'payment_method_id': "1",
//   'trending': "1",
//   'stock': "10",
//   'address': "null",
//   'length': "1",
//   'width': "1",
//   'height': "1",
//   'weight': "1",
//   'pickup': "satdobato",
//   'longitude': "75",
//   'latitude': "85",
//   'hyper_del': "1",
//   'seller_del': "0",
//   'story_display_days': "1",
//   'offers': "Seasonal Offers",
//   'youtube': "asdasdasd",
//   'piece_from[]': ["2", "7"],
//   'piece_to[]': ["6", "9"],
//   'rate[]': ["50", "45"],
// });

// // Adding a file to FormData
// formData.files.add(MapEntry(
//   'pictures',
//   await MultipartFile.fromFile(
//     'path_to_file/lZ13kF4j-/smog.png',
//     filename: 'smog.png',
//   ),
// ));
