import 'package:freezed_annotation/freezed_annotation.dart';

part 'product_model.freezed.dart';
part 'product_model.g.dart';

@freezed
class Product with _$Product {
  factory Product({
    String? id,
    // String? country_code,
    String? user_id,
    String? category_id,
    String? post_type_id,
    String? title,
    String? description,
    String? tags,
    String? price,
    String? negotiable,
    String? contact_name,
    // String? email,
    // String? phone,
    // String? phone_hidden,
    // String? address,
    // String? city_id,
    // String? lon,
    // String? lat,
    // String? ip_addr,
    // String? length,
    // String? width,
    // String? weight,
    // String? height,
    String? pickup,
    // String? longitude,
    // String? latitude,
    // String? hyper_del,
    // String? seller_del,
    String? visits,
    String? email_token,
    // String? phone_token,
    // String? tmp_token,
    // String? verified_email,
    // String? verified_phone,
    // String? accept_terms,
    // String? accept_marketing_offers,
    // String? is_permanent,
    // String? reviewed,
    // String? featured,
    // String? archived,
    // String? archived_at,
    // String? archived_manually,
    // String? deletion_mail_sent_at,
    // String? fb_profile,
    // String? partner,
    // String? discounted_price,
    // String? trending,
    // String? stock,
    // String? min_order,
    // String? samp_price,
    // String? text_one,
    // String? text_two,
    // String? ava_to,
    // String? branded,
    // String? wow,
    // String? offers,
    // String? story_display_days,
    // String? barcode,
    // String? b2b_pricing,
    // String? deleted_at,
    // String? created_at,
    // String? updated_at,
    String? image,
    double? avg_rating,
    List<dynamic>? savedByLoggedUser,
  }) = _Product;

  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);
}
